name: DreamTeam CI
on:
  push:
    branches: ["staging"]
  pull_request_target:
    branches: ["staging"]

jobs:
  local_deploy:
    if: github.repository_owner == 'TDT4D'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up DVC
        uses: iterative/setup-dvc@v2
        with:
          version: "3.59.1"
      - name: Fetch data
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          dvc pull -r gd-service
      - name: Build the Docker image
        run: docker compose build
      - name: Deploy the Docker image
        run: docker compose up -d
      - name: Check running containers
        run: docker ps
      - name: Shutdown the Docker image
        run: docker compose down --volumes
