name: Lint using Super-Linter

on: # yamllint disable-line rule:truthy
  push: null
  pull_request: null

# cancel any previously-started, yet still active runs of this workflow on the same branch
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter check mode
        uses: super-linter/super-linter@v7.3.0 # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # https://github.com/marketplace/actions/super-linter#configure-super-linter
          JAVA_FILE_NAME: "google_checks.xml"
          MULTI_STATUS: false
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSS_PRETTIER: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GIT_MERGE_CONFLICT_MARKERS: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GOOGLE_JAVA_FORMAT: true
          VALIDATE_HTML_PRETTIER: true
          VALIDATE_JAVA: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          VALIDATE_JSON: true
          VALIDATE_JSON_PRETTIER: true
          VALIDATE_JSX: true
          VALIDATE_JSX_PRETTIER: true
          VALIDATE_JUPYTER_NBQA_RUFF: true
          VALIDATE_MARKDOWN: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_MYPY: true
          VALIDATE_PYTHON_RUFF: true
          VALIDATE_TSX: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_TYPESCRIPT_PRETTIER: true
          VALIDATE_XML: true
          VALIDATE_YAML: true
          VALIDATE_YAML_PRETTIER: true
